### PR TITLE
Find_cell updated with ordered cell parameters; update_xds updated with a few more options; conflicts resolved

### PR DESCRIPTION
**Pull request by asdfdsa**

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi Bin, thanks for that! Looks mostly fine to me, I'm just wondering, why is the reference line problematic? `"Delete the reference line since it is sometimes problematic"`

**Comment by asdfdsa** [comment]
Hi, I don't know if you've seen this before, but after a few rounds of update_xds, the reference line just becomes weirdly encoded and super long, which makes the xds.inp file a few megabytes in size. I don't know the exact reason, but the easiest thing to do is just to remove it. This happened to both me (who ran xds on a machine through virtualbox) and many people in our group (running under WSL). I agree that this is not the perfect solution though

**Comment by stefsmeets** [comment]
Interesting, I haven't noticed this. If it's such a problem, maybe remove it by default!

**Comment by asdfdsa** [comment]
I agree, I did not try to find where went wrong but probably removing it from Instamatic XDS template directly is the best :)

**Pull request merged**
